config/routes.rb
Andrew90Proj2::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "/carts" => "carts#index", :as => "carts"
  match "/carts/:id/add" => "carts#add_item",  :as => "add"
  match "/carts/:id/update" => "carts#update_item", :as => "cart_item_update"
  match "/carts/:id/remove" => "carts#remove_item", :as => "cart_item_remove"
  match "/carts/save_to_list" => "carts#save_to_list", :as => "cart_to_list"

  match "/lists/add/:id" => "lists#add_item", :as => "list_add_item"
  match "/lists/update/:id" => "lists#update_item_quantity", :as => "list_update_item"
  match "/lists/:num/remove/:id" => "lists#remove_item", :as => "list_remove_item"
  match "/lists/search" => "lists#search", :as => "list_search"
  match "/lists/others/:id" => "lists#others", :as => "list_others" #try converting it into "/lists/index/others"
  match "/lists/:id/import_to_cart" => "lists#import_to_cart", :as => "import_to_cart"

  match "orders/confirm" => "orders#confirm", :as => "order_confirm"
  match "items/myItems" => "items#myItems", :as => "my_item"
  match "items/index_categories" => "items#index_categories", :as => "items_categories"
  match "users/account" => "users#account", :as => "user_account"

  resources :users
  resources :sessions
  resources :items
  resources :orders
  resources :lists
  resources :categories

  root :to => "items#index"
  

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :user_id, :name, :privacy, :desc

  belongs_to :user

  # List objects form many-to-many association with item objects.
  # This association is made possible through intermediate model called "ListItem"
  has_many :items, :through => :list_items
  has_many :list_items

  # Define constant for privacy settings
  def self.PRIVACY_PUBLIC
    0
  end

  # Define constant for privacy settings
  def self.PRIVACY_PRIVATE
    1
  end

  # This will import all the items in the list to the user's cart.
  def import_to_cart()

    cart = List.find(self.id).user.cart
    list_item=List.find(self.id).list_items.all

    #Importing the list will delete all the existing items in the cart
    cart.clear_cart

    list_item.each do |item|
      cart.cart_items.build(:item_id => item.item_id, :quantity => item.quantity)
    end
    cart.save
  end



end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  # Authorize shoppers for actions related to lists. Only shoppers can modify the lists
  before_filter :authorize_shopper, :only => [:new, :destroy, :edit, :update, :add_item, :update_item_quantity,:import_to_cart]

  def new
    @list=List.new
  end

  def create
    @list=current_user.lists.build(params[:list])
    if @list.save
      redirect_to lists_path, :notice => "New List"
    else
    end
  end

  # Let the shopper search for other user's shopping lists by email address
  def search
    user = User.where(:email => params[:search_data]).first

    if user #if such user exists
      redirect_to list_others_path(user.id)
    else #if such user doesn't exist
      redirect_to lists_path, :notice => "Couldn't find anyone"
    end
  end

  # shows the public list of the other user
  def others
    @lists=List.where(:user_id => params[:id], :privacy => List.PRIVACY_PUBLIC)
  end

  def index
    @public_lists=List.where(:user_id => current_user.id, :privacy => List.PRIVACY_PUBLIC)
    @private_lists=List.where(:user_id => current_user.id, :privacy => List.PRIVACY_PRIVATE)
  end

  # shows the list of corresponding params[:id]
  def show
    @list=List.find(params[:id])

    #If the specified list is private and other users try to access it through direct URL, the access will get denied
    if @list.privacy==List.PRIVACY_PRIVATE && @list.user.id!=current_user.id
      if current_user.status==User.STATUS_SHOPPER
        redirect_to lists_path, :notice => "The list is private!"
      else
        redirect_to items_path, :notice => "The list is private!"
      end
    end

  end

  # Delete the list
  def destroy
    @list=List.find(params[:id])
    list_items=ListItem.where(:list_id => @list.id)

    # Upon deleting the list, all the corresponding entries in list_items should also be removed
    list_items.each do |items|
      items.destroy
    end
    @list.destroy

    redirect_to lists_path :notice => "Successfully deleted!!"
  end

  def edit
    @list=List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    if list.update_attributes(params[:list])
      redirect_to list_path(list.id)
    else
      render action: "edit"
    end
  end

  # Add item to the selected list
  def add_item

    # If the user pressed "Add to Cart" without selecting a list
    if params[:list_num]==""
      redirect_to items_path, :notice => "Select a List!!!"
    else
      list_item=ListItem.where(:list_id=>params[:list_num], :item_id=>params[:id]).first_or_create
      redirect_to items_path, :notice=>"ADDED ITEM To The LIST!!"
    end
  end

  # Update item to the selected list
  def update_item_quantity

    # if the quantity is below 0, display notice that it's invalid quantity
    if params[:quantity].to_i < 0
      redirect_to list_path(params[:list_num]), :notice => "Invalid Quantity!"

    # if the quantity is set to 0, remove the item from the list
    elsif params[:quantity].to_i == 0
      redirect_to list_remove_item_path(:num => params[:list_num], :id => params[:id])

    # Else, update the quantity
    else
      l=ListItem.where(:list_id => params[:list_num], :item_id=>params[:id]).first_or_create
      l.update_quantity(params[:quantity])
      redirect_to list_path(params[:list_num]), :notice=>"Successfully updated!!"
    end
  end

  # Imports the whole list into the cart object. Existing items in the carts will be removed.
  def import_to_cart
    list=List.find(params[:id])
    list.import_to_cart
    redirect_to carts_path
  end

  # This method allows the shopper to remove unwanted items from the list
  def remove_item
    list_item=ListItem.where(:list_id=>params[:num], :item_id=>params[:id]).first
    list_item.destroy
    redirect_to list_path(params[:num])
  end


end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/edit.erb
<div class="title"> Edit List</div>

<%= render 'shared/list' %>

app/views/lists/index.erb
<div class="title"><%= "LISTS" %></div><br><br>

<div class="link"><%= link_to "Create new Lists", new_list_path %></div><br>

<div class="select">
<%= form_tag list_search_path do %>
    <%= text_field_tag :search_data, "type in other's e-mail" %>
    <td><%= submit_tag "Search"%></td>
<% end %>
</div><br><br>

<table>
  <tr>
    <th>Public Lists</th>
  </tr>

  <% @public_lists.each do |list| %>
    <tr>
        <td><%= "#{list.name}" %></td>
        <td><%= link_to "details", list_path(list.id) %></td>
    </tr>

  <% end %>

</table><br>

<table>
  <tr>
    <th>Private Lists</th>
    <th></th>
  </tr>

  <% @private_lists.each do |list| %>
      <tr>
        <td><%= "#{list.name}" %></td>
        <td><%= link_to "details", list_path(list.id) %></td>
      </tr>

  <% end %>

</table><br>

<div class="link">
  <%= link_to "Main Page", items_path %>
</div>

app/views/lists/new.erb
<div class="title"> Create new List</div>

<%= render 'shared/list' %>

app/views/lists/others.erb
<br>

<% @lists.each do |list| %>

    <p class="table_tag">
      <%= "#{list.name}" %>
      <%= link_to "details", list_path(list.id) %>
    </p>

<% end %><br>

<div class="link">
  <%= link_to "Back", lists_path %><br>
  <%= link_to "Main Page", items_path %>
</div>

app/views/lists/show.erb
<p class="table_tag"><%= "#{@list.name}" %></p>

<p class="table_tag">
  <%= "User : #{ @list.user.name}" %>
</p>
<p class="table_tag">
    <%= "About this list :" %><br>
    <%= @list.desc %>
</p>
<p class="table_tag">
  <%= "Last Updated at : #{@list.updated_at.to_date}" %>
</p>

<table>

  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Desired quantity</th>

  </tr>


  <% @list.list_items.each do |list_item| %>
      <% item=Item.find(list_item.item_id)  %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.name %></td>





        <% if current_user.id == @list.user.id %> <!-- If the owner of the list is looking at the list -->
            <%= form_tag list_update_item_path(:id=>item.id) do %>
                <%= hidden_field_tag :list_num, @list.id %>
                <td><%= number_field_tag :quantity, list_item.quantity %></td>
                <td><%= submit_tag "Update"%></td>
            <% end %>
        <% else %>
            <td><%= list_item.quantity %></td>
        <% end %>

        <td><%= "Updated at #{list_item.updated_at.to_date}" %></td>

        <%= form_tag add_path(:id=>item.id) do %>
            <%= hidden_field_tag :quantity, 1 %>
            <td><%= submit_tag "Add to Cart"%></td>
        <% end %>

      </tr>
  <% end %>
</table><br><br>

<div class="link">
    <% if current_user.id == @list.user.id %>
        <%= link_to "Import to Cart", import_to_cart_path(@list.id), :confirm => "This will remove existing items in the cart" %><br>
        <%= link_to "Edit",edit_list_path(@list.id) %><br>
        <%= link_to "Remove", @list, :confirm => "Are you sure you want to delete?", :method => :delete %><br><br>
        <%= link_to "Back", lists_path %>
    <% end %>
</div>