config/routes.rb
Andrew90Proj2::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "/carts" => "carts#index", :as => "carts"
  match "/carts/:id/add" => "carts#add_item",  :as => "add"
  match "/carts/:id/update" => "carts#update_item", :as => "cart_item_update"
  match "/carts/:id/remove" => "carts#remove_item", :as => "cart_item_remove"
  match "/carts/save_to_list" => "carts#save_to_list", :as => "cart_to_list"

  match "/lists/add/:id" => "lists#add_item", :as => "list_add_item"
  match "/lists/update/:id" => "lists#update_item_quantity", :as => "list_update_item"
  match "/lists/:num/remove/:id" => "lists#remove_item", :as => "list_remove_item"
  match "/lists/search" => "lists#search", :as => "list_search"
  match "/lists/others/:id" => "lists#others", :as => "list_others" #try converting it into "/lists/index/others"
  match "/lists/:id/import_to_cart" => "lists#import_to_cart", :as => "import_to_cart"

  match "orders/confirm" => "orders#confirm", :as => "order_confirm"
  match "items/myItems" => "items#myItems", :as => "my_item"
  match "items/index_categories" => "items#index_categories", :as => "items_categories"
  match "users/account" => "users#account", :as => "user_account"

  resources :users
  resources :sessions
  resources :items
  resources :orders
  resources :lists
  resources :categories

  root :to => "items#index"
  

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :desc, :name, :price, :keeper_id, :inStock, :category_id


  # Item objects form many-to-many association with cart objects.
  # This association is made possible through intermediate model called "CartItem"
  has_many :cart_items
  has_many :carts, :through => :cart_items

  # Item objects also form many-to-many association with list objects.
  # This association is made possible through intermediate model called "ListItem"
  has_many :list_items
  has_many :lists, :through => :list_items

  belongs_to :category

  # This method checks whether the requested items in the order are out of stock or not
  def self.check_validity(elements)
    # This array holds items that are low in stock
    out_of_stock_items=Array.new

    # Scan through the item list to check if any of the items are in low stock
    elements.each do |element|
      item=Item.find(element.item_id)
      if (item.inStock - element.quantity) < 0
        out_of_stock_items.push(element.item_id)
      end
    end

    # This array will contain items that are out of stock; it will be empty otherwise
    out_of_stock_items
  end


  # After the validation check has passed, this method will actually record changes in sales and stocks.
  def self.save_sales(elements)
    #if every item is in stock, update the sales and stock quantities
      elements.each do |element|
        item=Item.find(element.item_id)
        item.sales += element.quantity
        item.inStock -= element.quantity
        item.save
      end
    return nil
  end


  # This method displays which items are low in stock
  def self.show_low_stock_message(list)
    display="The current stock for"
    list.each do |item_id|
      item=Item.find(item_id)
      display<< " #{item.name} : #{item.inStock},"
    end
    display.chop << " !"
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  # Authorize shopkeepers only for the actions of "edit","destroy", and "new"
  # Shoppers and administrators can use other features
  before_filter :authorize_shopkeeper, :only => [:edit, :destroy, :new]

  def new
    @item=Item.new
    @categories=Category.all
  end

  def index
    @items=Item.all
    @categories=Category.all
    if current_user && current_user.status==User.STATUS_SHOPPER
      @lists=current_user.lists.all
    end
  end

  # This method is very similar to "index" except that it shows items in the selected category
  # GET /items and POST /items were already used by "index" and "create" methods => new action was required.
  def index_categories
    # if user selects "All categories", the blank value will be returned
    if params[:category_num]==""
      redirect_to items_path
    end

    # Only pass items under specific category
    @items=Item.where(:category_id => params[:category_num]).all
    @categories=Category.all
    if current_user && current_user.status==User.STATUS_SHOPPER
      @lists=current_user.lists.all
    end
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @categories=Category.all
  end

  # This method is triggered when the shopkeeper wants to create an item entry
  def create
    @item=Item.new(params[:item])
    if @item.save
      redirect_to root_url, :notice => "Successfully created"
    else
    end
  end

  # This method is triggered when the shopkeeper wants to modify an item entry
  def update
    item = Item.find(params[:id])
    if item.update_attributes(params[:item])
      redirect_to item_path(item.id), notice: "Successfully updated item!"
    else
      render action: "edit"
    end
  end

  # This method is triggered when the shopkeeper wants to take a look at only the items supplied by him
  def myItems
    @items=Item.where(:keeper_id => current_user.id)
  end


  # This method is triggered when the shopkeeper wants to remove an item entry
  def destroy
    @item=Item.find(params[:id])
    @item.destroy

    redirect_to items_path :notice => "Successfully deleted!!"
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.erb
<div class="title"> Editing item</div>

<%= render 'shared/form' %>

app/views/items/index.erb
<br>
<div class="title">Item list</div><br><br>

<div class="select">
    <%= form_tag items_categories_path do %>
        <td><%= select_tag "category_num",options_from_collection_for_select(@categories, "id", "name"), :prompt => "All categories"%></td>
        <td><%= submit_tag "Show" %></td>
    <% end %>
</div><br>

<table>
  <tr>
    <th>ID</th>
    <th>Category</th>
    <th>Name</th>
    <th>Price</th>
    <th>Stock</th>
  </tr>


  <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.category.name %></td>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= item.inStock %></td>

        <td><%= link_to "Details", item_path(item.id) %></td>

        <% if current_user && current_user.status==User.STATUS_SHOPPER %>
            <%= form_tag add_path(item.id) do %>
                <td><%=  number_field_tag :quantity, nil, :class =>"num" %></td>
                <td><%= submit_tag "Add to Cart"%></td>
            <% end %>
            <%= form_tag list_add_item_path(item.id) do %>
                <td><%= select_tag "list_num",options_from_collection_for_select(@lists, "id", "name"), :prompt => "Select a List" %></td>
                <td><%= submit_tag "Add to List" %></td>
            <% end %>


            <% if false %>
            <td><%= link_to "Add to List",list_add_item_path(:id=>item.id) %></td>
            <% end %>
      <% end %>
      </tr>
  <% end %>
</table>



<br><br><br>

<div class="link">
    <% if current_user %>
        <% if current_user.status==User.STATUS_SHOPPER%>
            <%= link_to "View My Past Orders", orders_path  %>
        <% elsif current_user.status==User.STATUS_SHOPKEEPER %>
            <%= link_to "New Item", new_item_path %><br>
            <%= link_to "My Items", my_item_path %><br>
            <%= link_to "View Customers' Orders", orders_path %>
         <% else %> <!-- If the user is administrator -->
            <%= link_to "New Category", new_category_path %>
            <%= link_to "Categories", categories_path %>
        <% end %>
    <% end %>
</div>

app/views/items/index_categories.erb
<br>
<div class="title">Item list</div><br><br>


<div class="select">
  <%= form_tag items_categories_path do %>
      <td><%= select_tag "category_num",options_from_collection_for_select(@categories, "id", "name"), :prompt => "All categories"%></td>
      <td><%= submit_tag "Show" %></td>
  <% end %>
</div><br>


<table>
  <tr>
    <th>ID</th>
    <th>Category</th>
    <th>Name</th>
    <th>Price</th>
    <th>Stock</th>
  </tr>


  <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.category.name %></td>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= item.inStock %></td>

        <td><%= link_to "Details", item_path(item.id) %></td>

        <% if current_user && current_user.status==User.STATUS_SHOPPER %>
            <%= form_tag add_path(item.id) do %>
                <td><%=  number_field_tag :quantity, nil, :class =>"num" %></td>
                <td><%= submit_tag "Add to Cart"%></td>
            <% end %>
            <%= form_tag list_add_item_path(item.id) do %>
                <td><%= select_tag "list_num",options_from_collection_for_select(@lists, "id", "name"), :prompt => "Select a List" %></td>
                <td><%= submit_tag "Add to List" %></td>
            <% end %>


            <% if false %>
                <td><%= link_to "Add to List",list_add_item_path(:id=>item.id) %></td>
            <% end %>
        <% end %>
      </tr>
  <% end %>
</table>



<br><br><br>

<div class="link">
  <% if current_user %>
      <% if current_user.status==User.STATUS_SHOPPER%>
          <%= link_to "View My Past Orders", orders_path  %>
      <% elsif current_user.status==User.STATUS_SHOPKEEPER %>
          <%= link_to "New Item", new_item_path %><br>
          <%= link_to "My Items", my_item_path %><br>
          <%= link_to "View Customers' Orders", orders_path %>
      <% else %>
          <%= link_to "New Category", new_category_path %>
          <%= link_to "Categories", categories_path %>
      <% end %>
  <% end %>
</div>

app/views/items/myItems.erb
<div class="title">Items list</div><br>

<table>
  <tr>
    <th>ID</th>
    <th>Category</th>
    <th>Name</th>
    <th>Price</th>
    <th>Stock</th>
    <th>Accumulated Sales</th>
  </tr>

  <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.category.name %></td>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= item.inStock %></td>
        <td><%= item.sales %></td>
        <td><%= link_to "Details", item_path(item.id) %></td>
      </tr>
  <% end %>
</table><br>

<div class="link">
  <%= link_to "Back to Main", items_path %>
</div>

app/views/items/new.erb
<h1>New Items</h1>

<%= render 'shared/form' %>

app/views/items/show.erb
<div class="item">
    <p><%= "Item #{@item.id} : #{@item.name}"%></p>
    <p><%= "Category : #{@item.category.name}" %></p>
    <p><%= "Price : #{@item.price}"%></p>
    <p><%= "Supplier : #{User.find(@item.keeper_id).name} (Supplier ID : #{@item.id})" %></p>
    <p><%= "Description :  #{@item.desc}" %></p><br>

    <% if current_user && current_user.status==User.STATUS_SHOPPER %>
        <%= form_tag add_path(@item.id) do %>
            <td><%=  number_field_tag :quantity, :class => "num" %></td>
            <td><%= submit_tag "Add to cart"%></td>
        <% end %>
    <% end %>
</div><br>

<div class="link">
    <% if current_user && (current_user.id==@item.keeper_id) %>
        <%= link_to "Edit", edit_item_path(@item.id) %><br>
        <%= link_to "Remove", @item, :confirm => "Are you sure you want to delete?", :method => :delete %><br>
    <% end %>
    <%= link_to "Back to Main", items_path %>
</div>