config/routes.rb
Andrew90Proj2::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "/carts" => "carts#index", :as => "carts"
  match "/carts/:id/add" => "carts#add_item",  :as => "add"
  match "/carts/:id/update" => "carts#update_item", :as => "cart_item_update"
  match "/carts/:id/remove" => "carts#remove_item", :as => "cart_item_remove"
  match "/carts/save_to_list" => "carts#save_to_list", :as => "cart_to_list"

  match "/lists/add/:id" => "lists#add_item", :as => "list_add_item"
  match "/lists/update/:id" => "lists#update_item_quantity", :as => "list_update_item"
  match "/lists/:num/remove/:id" => "lists#remove_item", :as => "list_remove_item"
  match "/lists/search" => "lists#search", :as => "list_search"
  match "/lists/others/:id" => "lists#others", :as => "list_others" #try converting it into "/lists/index/others"
  match "/lists/:id/import_to_cart" => "lists#import_to_cart", :as => "import_to_cart"

  match "orders/confirm" => "orders#confirm", :as => "order_confirm"
  match "items/myItems" => "items#myItems", :as => "my_item"
  match "items/index_categories" => "items#index_categories", :as => "items_categories"
  match "users/account" => "users#account", :as => "user_account"

  resources :users
  resources :sessions
  resources :items
  resources :orders
  resources :lists
  resources :categories

  root :to => "items#index"
  

end

app/models/category.rb
# Category model is for classifications of items
class Category < ActiveRecord::Base

  attr_accessible :name, :description

  # category contains many items
  has_many :items
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # Only authorize administrators to be able to interact with categories
  before_filter :authorize_administrator

  def new
    @category=Category.new
  end

  def create
    @category=Category.new(params[:category])
    if @category.save
      redirect_to root_url, :notice => "Successfully created"
    else
    end
  end

  def index
    @categories=Category.all
  end

  def show
    @category=Category.find(params[:id])
  end

  def edit
    @category=Category.find(params[:id])
  end

  def update
    category = Category.find(params[:id])
    if category.update_attributes(params[:category])
      redirect_to category_path(category.id)
    else
      render action: "edit"
    end
  end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.erb
<div class="title"> Edit Category </div>

<%= render "shared/category" %>

app/views/categories/index.erb
<div class="title"> Categories </div><br>

<table>
  <tr>
    <th>ID</th>
    <th>Category</th>
  </tr>


  <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td><%= link_to "Details", category_path(category.id) %></td>
      </tr>
  <% end %>
</table><br><br>

<div class="link">
  <%= link_to "Main Page", items_path %>
</div>

app/views/categories/new.erb
<div class="title"> New Category </div>

<%= render "shared/category" %>

app/views/categories/show.erb
<div class="title"><%= "Category #{@category.id}" %></div>

<div class="item">
  <p><%= "Category : #{@category.name}" %></p>
  <p><%= "Description :  #{@category.description}" %></p><br>
</div><br>

<div class="link">
      <%= link_to "Edit", edit_category_path(@category.id) %><br>
      <%= link_to "Back to Main", items_path %>
</div>