config/routes.rb
Andrew90Proj2::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "/carts" => "carts#index", :as => "carts"
  match "/carts/:id/add" => "carts#add_item",  :as => "add"
  match "/carts/:id/update" => "carts#update_item", :as => "cart_item_update"
  match "/carts/:id/remove" => "carts#remove_item", :as => "cart_item_remove"
  match "/carts/save_to_list" => "carts#save_to_list", :as => "cart_to_list"

  match "/lists/add/:id" => "lists#add_item", :as => "list_add_item"
  match "/lists/update/:id" => "lists#update_item_quantity", :as => "list_update_item"
  match "/lists/:num/remove/:id" => "lists#remove_item", :as => "list_remove_item"
  match "/lists/search" => "lists#search", :as => "list_search"
  match "/lists/others/:id" => "lists#others", :as => "list_others" #try converting it into "/lists/index/others"
  match "/lists/:id/import_to_cart" => "lists#import_to_cart", :as => "import_to_cart"

  match "orders/confirm" => "orders#confirm", :as => "order_confirm"
  match "items/myItems" => "items#myItems", :as => "my_item"
  match "items/index_categories" => "items#index_categories", :as => "items_categories"
  match "users/account" => "users#account", :as => "user_account"

  resources :users
  resources :sessions
  resources :items
  resources :orders
  resources :lists
  resources :categories

  root :to => "items#index"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping Cart</title>
  <link rel="stylesheet" href="index.css"/>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<br>
<div id="welcome">
  Welcome to 6.170 Shopping Mall
</div>

<!-- This navigation bar is always shown on the top, so the user can always access it-->
<div class="user_nav">
   <% if current_user%>
      Welcome!! <%= current_user.name %> <br>
      <%= link_to "My Account", user_account_path %>
      <%= link_to "Log out", log_out_path %><br>
      <% if current_user.status==User.STATUS_SHOPPER %>
          <%= link_to "My Shopping Cart", carts_path %><br>
          <%= link_to "My Shopping Lists", lists_path %>
      <% end %>

  <% else %>
      <%=  link_to "Log in", log_in_path %>
      <%=  link_to "Sign in", sign_up_path %>
  <% end %>
</div>

<div id="page">
    <% if flash[:notice] %>
        <h3><p class="flash-notice"><%= flash[:notice] %></p></h3>
    <% end %>
</div>


<%= yield %>

</body>
</html>